import express from "express"
import cors from "cors"
import { Server } from "@modelcontextprotocol/sdk/server/index.js"
import { SSEServerTransport } from "@modelcontextprotocol/sdk/server/sse.js"
import {
	CallToolRequestSchema,
	ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js"
import { CDPService } from "./cdp_service.js"
import "dotenv/config"

// Initialize CDP Service
const cdpService = new CDPService((msg, type) => {
	console.log(`[CDP|${type || "info"}] ${msg}`)
})

// Create MCP Server
const server = new Server(
	{
		name: "antigravity-mcp",
		version: "1.0.0",
	},
	{
		capabilities: {
			tools: {},
		},
	},
)

// Define Tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
	return {
		tools: [
			{
				name: "ag_send_message",
				description: "Send a text message to the Antigravity chat.",
				inputSchema: {
					type: "object",
					properties: {
						text: { type: "string", description: "The text message to send." },
						attachments: {
							type: "array",
							description:
								"Optional list of file attachments to include with the message.",
							items: {
								type: "object",
								properties: {
									name: {
										type: "string",
										description: "Filename (e.g., image.png, log.txt)",
									},
									mimeType: {
										type: "string",
										description: "MIME type (e.g., image/png, text/plain)",
									},
									data: {
										type: "string",
										description: "Base64 encoded string of the file content.",
									},
								},
								required: ["name", "mimeType", "data"],
							},
						},
					},
					required: ["text"],
				},
			},
			{
				name: "ag_screenshot",
				description: "Capture a screenshot of the Antigravity workspace.",
				inputSchema: {
					type: "object",
					properties: {},
					required: [],
				},
			},
			{
				name: "ag_get_status",
				description:
					"Get the current chat title, active model, and conversational mode (Planning or Fast).",
				inputSchema: {
					type: "object",
					properties: {},
					required: [],
				},
			},
			{
				name: "ag_switch_model",
				description: "Switch the active AI model.",
				inputSchema: {
					type: "object",
					properties: {
						modelName: {
							type: "string",
							description:
								"Name of the model to switch to (e.g., claude, gemini, o3-mini).",
						},
					},
					required: ["modelName"],
				},
			},
			{
				name: "ag_switch_mode",
				description: "Switch between Planning and Fast modes.",
				inputSchema: {
					type: "object",
					properties: {
						mode: {
							type: "string",
							description: "Mode to switch to (planning or fast).",
						},
					},
					required: ["mode"],
				},
			},
			{
				name: "ag_new_chat",
				description: "Start a new chat session in Antigravity.",
				inputSchema: {
					type: "object",
					properties: {},
					required: [],
				},
			},
			{
				name: "ag_stop_generation",
				description: "Stop the ongoing AI text generation.",
				inputSchema: {
					type: "object",
					properties: {},
					required: [],
				},
			},
			{
				name: "ag_click_approval",
				description:
					"Click the approval/rejection button in Antigravity for commands or file modifications.",
				inputSchema: {
					type: "object",
					properties: {
						allow: {
							type: "boolean",
							description: "True to allow/approve, false to reject/cancel.",
						},
					},
					required: ["allow"],
				},
			},
			{
				name: "ag_get_list_models",
				description: "Get the list of available models in the dropdown.",
				inputSchema: {
					type: "object",
					properties: {},
					required: [],
				},
			},
			{
				name: "ag_check_approval_required",
				description: "Check if there is an active approval request pending in the UI.",
				inputSchema: {
					type: "object",
					properties: {},
					required: [],
				},
			},
			{
				name: "ag_wait_for_completion",
				description:
					"Blocks and waits for AI text generation to complete or for an approval request to appear. Call this after ag_send_message. The tool returns immediately if an approval is required, or when generation naturally completes.",
				inputSchema: {
					type: "object",
					properties: {
						timeoutMs: {
							type: "number",
							description:
								"Maximum time to wait in milliseconds. Defaults to 600000 (10 minutes).",
						},
					},
					required: [],
				},
			},
			{
				name: "ag_get_last_response",
				description: "Get the last response text generated by the AI.",
				inputSchema: {
					type: "object",
					properties: {},
					required: [],
				},
			},
		],
	}
})

// Handle Tool Execution
server.setRequestHandler(CallToolRequestSchema, async (request) => {
	const { name, arguments: args } = request.params

	try {
		switch (name) {
			case "ag_send_message": {
				const text = args.text
				const attachments = args.attachments || []
				if (!text) throw new Error("text argument is required")
				const injectRes = await cdpService.injectMessage(text, attachments)
				if (!injectRes || !injectRes.ok) {
					return {
						content: [
							{
								type: "text",
								text: JSON.stringify(injectRes || { error: "Failed to inject message" }),
							},
						],
					}
				}

				// Wait for Antigravity to finish generating the response
				const completionRes = await cdpService.waitForCompletion(120000) // wait up to 2 mins

				// If approval is required, return that status immediately so the agent can react
				if (completionRes.status === "approval_required") {
					return { content: [{ type: "text", text: JSON.stringify(completionRes) }] }
				}

				// Otherwise, fetch the final response text
				const finalRes = await cdpService.getLastResponse()
				return {
					content: [
						{
							type: "text",
							text:
								finalRes && finalRes.text ? finalRes.text : JSON.stringify(completionRes),
						},
					],
				}
			}
			case "ag_screenshot": {
				const buffer = await cdpService.getScreenshot()
				if (!buffer) throw new Error("Failed to capture screenshot")
				return {
					content: [
						{ type: "text", text: "Screenshot captured successfully." },
						{
							type: "image",
							data: buffer.toString("base64"),
							mimeType: "image/png",
						},
					],
				}
			}
			case "ag_get_status": {
				const title = (await cdpService.getCurrentTitle()) || "Unknown"
				const model = (await cdpService.getCurrentModel()) || "Unknown"
				const mode = (await cdpService.getCurrentMode()) || "Unknown"
				return {
					content: [{ type: "text", text: JSON.stringify({ title, model, mode }) }],
				}
			}
			case "ag_switch_model": {
				const modelName = args.modelName
				if (!modelName) throw new Error("modelName argument is required")
				const res = await cdpService.switchModel(modelName)
				return {
					content: [{ type: "text", text: JSON.stringify(res) }],
				}
			}
			case "ag_switch_mode": {
				const mode = args.mode
				if (!mode) throw new Error("mode argument is required")
				const res = await cdpService.switchMode(mode)
				return {
					content: [{ type: "text", text: JSON.stringify(res) }],
				}
			}
			case "ag_new_chat": {
				const res = await cdpService.startNewChat()
				return {
					content: [
						{
							type: "text",
							text: res ? "New chat started successfully." : "Failed to start new chat.",
						},
					],
				}
			}
			case "ag_stop_generation": {
				const res = await cdpService.stopGeneration()
				return {
					content: [
						{
							type: "text",
							text: res
								? "Generation stopped successfully."
								: "Failed to stop generation (or not generating).",
						},
					],
				}
			}
			case "ag_click_approval": {
				if (typeof args.allow !== "boolean")
					throw new Error("allow boolean argument is required")
				const res = await cdpService.clickApproval(args.allow)
				return {
					content: [{ type: "text", text: JSON.stringify(res) }],
				}
			}
			case "ag_get_list_models": {
				const res = await cdpService.getModelList()
				return {
					content: [{ type: "text", text: JSON.stringify(res) }],
				}
			}
			case "ag_check_approval_required": {
				const res = await cdpService.checkApprovalRequired()
				return {
					content: [{ type: "text", text: JSON.stringify(res || { required: false }) }],
				}
			}
			case "ag_wait_for_completion": {
				const timeoutMs = args.timeoutMs || 600000
				const res = await cdpService.waitForCompletion(timeoutMs)
				return {
					content: [{ type: "text", text: JSON.stringify(res) }],
				}
			}
			case "ag_get_last_response": {
				const res = await cdpService.getLastResponse()
				return {
					content: [{ type: "text", text: JSON.stringify(res || { text: null }) }],
				}
			}
			default:
				throw new Error(`Unknown tool: ${name}`)
		}
	} catch (error) {
		return {
			content: [{ type: "text", text: `Error executing tool ${name}: ${error.message}` }],
			isError: true,
		}
	}
})

// Set up Express server for SSE Transport
const app = express()
app.use(cors())

let transport

app.get("/sse", async (req, res) => {
	transport = new SSEServerTransport("/messages", res)
	await server.connect(transport)

	// Auto-connect to CDP target so tools are immediately available
	cdpService.ensureCDP().then((cdp) => {
		if (cdp) {
			console.log("✅ MCP auto-connected to Antigravity CDP target")
		} else {
			console.log("❌ Failed to automatically connect to Antigravity. (Is it running?)")
		}
	})

	console.log("Client connected to SSE endpoint")
})

app.post("/messages", async (req, res) => {
	if (!transport) {
		res.status(400).send("No active SSE connection")
		return
	}
	await transport.handlePostMessage(req, res)
})

// Port configuration
const PORT = process.env.MCP_PORT || 3000
const HOST = process.env.MCP_HOST || "0.0.0.0"

app.listen(PORT, HOST, () => {
	console.log(`🚀 Antigravity MCP Server running on http://${HOST}:${PORT}/sse`)
	console.log(`Add this URL to your MCP client configuration (e.g., OpenClawAgent).`)
	console.log(`\n======================================================`)
	console.log(`🛡️  MCP サーバーは現在【駐屯中（プロセス実行中）】です。`)
	console.log(`❌  終了処理は [Ctrl + C] を押してプロセスを停止してください。`)
	console.log(`======================================================\n`)
})

// Keep the process alive in the terminal until Ctrl+C is pressed
process.stdin.resume()
